### ISSUE TITLE
how can i play the game without keyboard?

### ISSUE THREAD

**Issue by ddeellttaa** [Randonee1/Advanced-Language-Programming#3]

**Comment by Randonee1** [comment]
With your feet

**Comment by ddeellttaa** [comment]
呵呵



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月08日 09:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Randonee1/Advanced-Language-Programming] how can i play the game without keyboard? (Issue #3) |

With your feet
